# Generated by Django 2.1.7 on 2019-04-30 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190430_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 30, 11, 47, 7, 174474, tzinfo=utc), null=True),
        ),
    ]
