# Generated by Django 2.1.7 on 2019-04-30 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190430_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 30, 14, 6, 9, 715778, tzinfo=utc), null=True),
        ),
    ]
